### ISSUE TITLE
Проблемы с JRE

### ISSUE THREAD

**Issue by Paylek** [gdevby/desktop-starter-launch-update-bootstrap#32]
При удалении вручную jre_default и cache и запуске лаунчера возникает ошибка
java.nio.file.NoSuchFileException: /home/pavel/testDirectory6/desktop-starter-launch-update-bootstrap/starter-core/target/starter/jre_default
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at by.gdev.util.DesktopUtil.getJavaRun(DesktopUtil.java:233)
	at by.gdev.component.Starter.runApp(Starter.java:267)
	at by.gdev.Main.main(Main.java:45)

**Comment by robertmakrytski** [comment]
1)we can delete /home/robert/.tlauncher/starter/jre_default/jre-17.0.9-linux-x64. It should understand that we need to reinstall java.

**Comment by emanual014** [comment]
how get jre name (jre1.8.0_281)
